spring:
  datasource:
    url: jdbc:mysql://localhost:3306/post_service?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: rlawltjr123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    time-zone: Asia/Seoul

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

  session:
    store-type: none   # ✅ 세션 저장소 완전 비활성화

server:
  servlet:
    session:
      timeout: 0          # ✅ 세션 즉시 만료
      persistent: false   # ✅ 세션 저장하지 않음
      tracking-modes: cookie  # ✅ URL 세션 트래킹도 비활성화
